[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88

[tool.mypy]
ignore_missing_imports = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
strict_equality = "True"
warn_redundant_casts = "True"
warn_unused_ignores = "True"
show_error_codes = "True"
disallow_any_generics = "True"
disallow_incomplete_defs = "True"
disallow_untyped_defs = "True"